### ISSUE TITLE
Add English comments

### ISSUE THREAD

**Issue by upintheairsheep** [builtbybel/Appcopier#3]
The comments in the code are in German unlike the English README, please add English comments either with or replacing the German comments

**Comment by Belim** [comment]
the code is not online yet :open_mouth: You mean assembly, right?

**Comment by upintheairsheep** [comment]
> the code is not online yet 😮 You mean assembly, right?

Oh, I was looking for the paths and code, but the assembly files have comments in German, as I respect other languages, you can keep them if it’s easier for you, but adding translations in English should let other programmers understand due to being the lingua franca of programming, the internet, and Earth itself.
